Update index.html
RomanDovgii/eco-com pull request #2
Opened 2020-06-12 11:17 UTC by goodlufe

2020-06-12 11:30 UTC, RomanDovgii requested changes
Ну смотри, косяки нужно устранить, а также нужно сосредоточиться на работе.
Понимаю, что родители просят помощи и т.д., но объясни им, что у тебя сейчас нет времени и тебе нужно сосредоточиться на учебе. У нас осталось 3 дня до показа, а у тебя работа практически не начата.

2020-06-12 11:30 UTC, RomanDovgii commented on index.html
> +    </h1>
Неправильно.
Header - обозначает блок сайта, который всегда находится сверху, он не может быть внутри текстового элемента, которым является h1 (обозначает заголовок первого уровня).

2020-06-12 11:30 UTC, RomanDovgii commented on index.html
> +    </section>
На сайте желателен один `<nav>`, который оборачивает ненумерованный список с элементами. 
т.е. у тебя должен быть nav > ul > li (тег для каждого элемента в данном меню).

Section использован верно - молодец.

2020-06-12 11:30 UTC, RomanDovgii commented on index.html
> +    </aside>
`<aside>` здесь даром не нужен.
Зачем ты сделал обертку из `<p>`? У тебя тут не текст, а список элементов (если что, то p = paragraph, то есть параграф). По поводу списка - пока что ок.

2020-06-12 11:30 UTC, RomanDovgii commented on index.html
> +        <article>Производство качественных фильтровальных элементов и металллических каркасов</article>
Зачем здесь `<article>`? 
Тебе достаточно `<p>`.

2020-06-12 11:32 UTC, goodlufe commented on index.html
> +        <article>Производство качественных фильтровальных элементов и металллических каркасов</article>
понял ,исправлю будт вопросы писать тут?

2020-06-12 12:23 UTC, RomanDovgii commented on index.html
> +        <article>Производство качественных фильтровальных элементов и металллических каркасов</article>
Еп, есть вопросы - пиши здесь. Тут удобно работать с кодом.

2020-06-12 12:41 UTC, goodlufe commented on index.html
> +        <article>Производство качественных фильтровальных элементов и металллических каркасов</article>
исправил ,пришло?

2020-06-12 12:48 UTC, RomanDovgii requested changes
Так, просмотрел, а где у тебя номер телефона и электронная почта, которые в правом верхнем углу?

2020-06-12 12:48 UTC, RomanDovgii commented on index.html
>      </h1>
p = paragraph
Видишь ли ты здесь параграф?
Если его нет, то h1 тебе достаточно, потому что это заголовок. Заголовок не должен содержать в себе параграфов.

2020-06-12 12:48 UTC, RomanDovgii commented on index.html
> +        </nav>
Молодец, уже лучше, тут больше не нужно править, оберни только элементы внутри ли в ссылки (`<a>`)

2020-06-12 12:48 UTC, RomanDovgii commented on index.html
> +    </p>
Про `<p>` я говорил, покажи где тут параграф.

2020-06-12 12:49 UTC, RomanDovgii commented on index.html
>      </h1>
Тут в чем суть, убери тут h1 сейчас, потом объясню, что с ним делать.

2020-06-12 12:50 UTC, RomanDovgii commented on index.html
>      </h1>
`<p>` здесь только и нужен, потому что здесь текст есть, но этот текст не является заголовком, а является простым текстом, поясняющим, что это вообще за сайт.

2020-06-12 12:51 UTC, RomanDovgii commented on index.html
> +    </p>
Его тут нет, следовательно, `<p>` не нужен

2020-06-12 13:00 UTC, goodlufe commented on index.html
> +    </p>
Исправил,теперь как?

2020-06-12 13:10 UTC, RomanDovgii requested changes
Читай не только лишь основные поправки, но и комментарии к ним, я там более подробно рассказываю как исправить ошибки

2020-06-12 13:10 UTC, RomanDovgii commented on index.html
>      </header>
Это у нас что? Я же тебе говорил про header в самом начале

2020-06-12 13:10 UTC, RomanDovgii commented on index.html
>      </h1>
Ты читал комментарии, которые были также добавлены к этому моменту?

2020-06-12 13:10 UTC, RomanDovgii commented on index.html
>      </section>
Все, молодец, хорошо сделал

2020-06-12 13:10 UTC, RomanDovgii commented on index.html
> +    </ul>
Еще можешь в секцию обернуть и не забудь добавить заголовок, который есть на макете.

2020-06-12 13:11 UTC, RomanDovgii commented on index.html
>      </header>
> Header - обозначает блок сайта, который всегда находится сверху, он не может быть внутри текстового элемента, которым является h1 (обозначает заголовок первого уровня).

2020-06-12 13:39 UTC, RomanDovgii requested changes
В первой части все еще нет разметки для логотипа, телефона и имейла

2020-06-12 13:39 UTC, RomanDovgii commented on index.html
> +    </p>
Молодец

2020-06-12 13:39 UTC, RomanDovgii commented on index.html
> +    </section>
Молодец, но все еще забыт заголовок

2020-06-12 19:00 UTC, RomanDovgii requested changes
Молодец, уже лучше, но читай то, что я пишу в самом начале каждого ревью, потому что до сих пор не вижу номера телефона и электронной почты вверху

2020-06-12 19:00 UTC, RomanDovgii commented on index.html
> +    </section>
Внеси h2 внутрь секции

2020-06-12 19:00 UTC, RomanDovgii commented on index.html
> +    </section>
То же, что и в прошлом, также опечатки поправь

2020-06-12 19:00 UTC, RomanDovgii commented on index.html
>      </section>
Тоже h2 внутрь секции

2020-06-12 19:00 UTC, RomanDovgii commented on index.html
>      </p>
Их логично в одну секцию, не забудь про номер телефона и почту в этой секции

2020-06-13 10:09 UTC, goodlufe commented on index.html
>      </p>
а номер телефона и почту в какой тег кидатиь?

2020-06-13 10:17 UTC, goodlufe commented on index.html
>      </p>
И что в секцию кидать h1 или p?

2020-06-13 10:52 UTC, RomanDovgii requested changes
Читай комменты

2020-06-13 10:52 UTC, RomanDovgii commented on index.html
> +        </section>
Это все в одну секцию

2020-06-13 10:52 UTC, RomanDovgii commented on index.html
> +        </section>
Молодец, я доволен

2020-06-13 10:52 UTC, RomanDovgii commented on index.html
> +        </section>
Молодец

2020-06-13 10:53 UTC, RomanDovgii requested changes

2020-06-13 10:53 UTC, RomanDovgii commented on index.html
> +    </section>
А где разметка для логотипа?

2020-06-13 11:54 UTC, RomanDovgii requested changes

2020-06-13 11:54 UTC, RomanDovgii commented on index.html
>      </h1>
При чем тут h1? Где ты здесь видишь заголовок?

2020-06-13 11:54 UTC, RomanDovgii commented on index.html
> +        </a>
Ок

2020-06-13 15:51 UTC, RomanDovgii requested changes

2020-06-13 15:51 UTC, RomanDovgii commented on index.html
> +    </section>
Ошибся в разделении на секции, подумай, где неправильно и почему

2020-06-13 15:51 UTC, RomanDovgii commented on index.html
>      </a>
точку поставь в самом начале пути, убери из названия изображения заглавную букву здесь и у самого файла в папке

2020-06-13 15:53 UTC, RomanDovgii requested changes

2020-06-13 15:53 UTC, RomanDovgii commented on index.html
> +            <img src="/img/Eco-com2.png">
убери заглавные буквы из названия, это логотип вообще другой компании, так что назови его другими словами.

2020-06-13 15:53 UTC, RomanDovgii commented on index.html
> +        <h3>Ознакомьтесь со всей нашей продукцией и услугами</h3>
Находится не в своей секции

2020-06-13 19:57 UTC, goodlufe commented on index.html
> +        <h3>Ознакомьтесь со всей нашей продукцией и услугами</h3>
отправил в названии изображения я не могу убрать заглавную ,т.к. при попытке сделать маленькую возвращает обратно к заглавной, и в какой секции доэно быть?

2020-06-14 08:06 UTC, RomanDovgii requested changes

2020-06-14 08:06 UTC, RomanDovgii commented on index.html
>      </section>
Обоснуй данную секцию

2020-06-14 08:07 UTC, RomanDovgii commented on index.html
> +        <h3>Ознакомьтесь со всей нашей продукцией и услугами</h3>
Теперь тебе нужно удалить этот файл, запушить, и вновь добавить этот файл без заглавной

2020-06-14 08:08 UTC, RomanDovgii requested changes

2020-06-14 08:08 UTC, RomanDovgii commented on index.html
>          </h3>
У этого должна быть своя секция, там даже целых две ссылки есть на скачивание каталогов

2020-06-14 13:21 UTC, RomanDovgii requested changes

2020-06-14 13:21 UTC, RomanDovgii commented on index.html
>      </section>
Двух ссылок до сих пор нет

2020-06-14 14:24 UTC, merged